fix grammar and spelling for solutions sections
threefoldfoundation/info_gridmanual pull request #256
Opened 2020-09-15 13:39 UTC by DylanVerstraete

2020-09-15 15:38 UTC, rkhamis approved these changes

2020-09-16 09:06 UTC, sasha-astiadi commented on src/3bot_sysadmin/admin_tools/3bot_packages.md
> +The __tfgrid_solutions__ package is a package that imports all the default solutions that the TF Grid provides.
TF Grid Solutions Package

2020-09-16 09:32 UTC, sasha-astiadi requested changes

2020-09-16 09:32 UTC, sasha-astiadi commented on src/3bot_sysadmin/admin_tools/3bot_packages.md
> +Makes it possible for assets (images, javascript, css) to be used across the 3Bot.
Javascript, CSS

2020-09-16 09:32 UTC, sasha-astiadi commented on src/3bot_sysadmin/admin_tools/3bot_packages.md
> +The __tfgrid_solutions__ package is a package that imports all the default solutions that the TF Grid provides.
__TF Grid Solutions__ Package

2020-09-16 09:32 UTC, sasha-astiadi commented on src/3bot_sysadmin/admin_tools/3bot_packages.md
> +### Farm management
Farm Management

2020-09-16 09:32 UTC, sasha-astiadi commented on src/3bot_sysadmin/admin_tools/3bot_packages.md
> +The farmmanagement package help your create and manage a TF Grid Farm.
The Farm Management

2020-09-16 09:32 UTC, sasha-astiadi commented on src/3bot_sysadmin/admin_tools/3bot_packages.md
> +Is a package that will host the marketplace on your 3Bot. The marketplace consists of extra solutions that you can deploy within a few clicks!
The Marketplace

2020-09-16 09:32 UTC, sasha-astiadi commented on src/3bot_sysadmin/admin_tools/3bot_packages.md
> +### Threebot deployer
3Bot Deployer

2020-09-16 09:32 UTC, sasha-astiadi commented on src/3bot_sysadmin/admin_tools/3bot_packages.md
> +### Stellar stats
Stellar Stats

2020-09-16 09:32 UTC, sasha-astiadi commented on src/3bot_sysadmin/admin_tools/3bot_packages.md
> +This package will host Visual Studio Code in the browser! Here you can interact with the 3Bot source code and edit it!
edit it online, directly on your hosted 3Bot.

2020-09-16 09:32 UTC, sasha-astiadi commented on src/3bot_sysadmin/admin_tools/3bot_packages.md
> +The admin package of the 3Bot makes it possible for a user to give access to other users.
The Admin Package

2020-09-16 09:32 UTC, sasha-astiadi commented on src/3bot_sysadmin/admin_tools/3bot_backup.md
> +The 3Bot backup is a service that backs up the data of your 3Bot, with this backup you can recover your 3Bot.
The 3Bot Backup is a service that backs up the data of your 3Bot, with this backup you can recover your 3Bot. 
 @sasha-astiadi

2020-09-16 09:32 UTC, sasha-astiadi commented on src/3bot_sysadmin/admin_tools/3bot_backup.md
>  ## Backing up
## Get Started on Backup

2020-09-16 09:32 UTC, sasha-astiadi commented on src/3bot_sysadmin/admin_tools/3bot_backup.md
> +The backup service has 2 options for hosted 3Bots:
Hosted 3Bot offers 2 different types of backup services:

2020-09-16 09:32 UTC, sasha-astiadi commented on src/3bot_sysadmin/admin_tools/3bot_backup.md
>  ### Marketplace backup
### Marketplace Backup

2020-09-16 09:32 UTC, sasha-astiadi commented on src/3bot_sysadmin/admin_tools/3bot_backup.md
> +> Backups of a hosted 3Bot will be stored by the 3Bot deployer service.
> Backups of a hosted 3Bot will be stored by the 3Bot Deployer service.

2020-09-16 09:32 UTC, sasha-astiadi commented on src/3bot_sysadmin/admin_tools/3bot_backup.md
> +The backup service only has one option for local 3Bot backups which is __Minio__.
Meanwhile, the local 3Bot only offers one type of backup service: Minio Backup

2020-09-16 09:32 UTC, sasha-astiadi commented on src/3bot_sysadmin/admin_tools/3bot_backup.md
> +The marketplace backup is a service that is installed by default when you initialize a 3Bot. It takes a snapshot of your data the moment your 3Bot is live.
The Marketplace Backup is a service that is installed by default when you initialize a 3Bot. It automatically takes a snapshot of your data the moment your 3Bot is live.

2020-09-16 09:32 UTC, sasha-astiadi commented on src/3bot_sysadmin/admin_tools/3bot_backup.md
>  ## Recovering with marketplace backup
## Recovering With The Marketplace Backup

2020-09-16 09:32 UTC, sasha-astiadi commented on src/3bot_sysadmin/admin_tools/3bot_backup.md
> +For a backup to be recovered you need to have following information:
For a backup to be recovered, the following information are mandatory to have:

2020-09-16 09:32 UTC, sasha-astiadi commented on src/3bot_sysadmin/admin_tools/3bot_backup.md
>  - The password associated with it.
- The password associated to it.

2020-09-16 09:32 UTC, sasha-astiadi commented on src/3bot_sysadmin/admin_tools/3bot_backup.md
>  ## Recovering with minio backup
## Recovering with MinIO Backup

2020-09-16 09:32 UTC, sasha-astiadi commented on src/3bot_sysadmin/admin_tools/3bot_backup.md
> +Recovering a backup with minio requires some manual work. It backs up the configuration in `~/.config/jumpscale` and if autobackup is enabled it'll do so every 24 hours.
Recovering a backup with MinIO requires some manual work. It backs up the configuration in `~/.config/jumpscale` and if autobackup is enabled, it will do so every 24 hours.

2020-09-16 09:32 UTC, sasha-astiadi commented on src/3bot_sysadmin/admin_tools/3bot_backup.md
> +Working with the backups with minio requires some manual work. It backs up the configuration in `~/.config/jumpscale`, and if autobackup is enabled it'll do so every 24 hours.
Working with the backups with MinIO requires some manual work. It backs up the configuration in `~/.config/jumpscale`, and if autobackup is enabled it'll do so every 24 hours.

2020-09-16 09:32 UTC, sasha-astiadi commented on src/3bot_sysadmin/admin_tools/3bot_backup.md
>  ## Recovering with marketplace backup
## Recovering with Marketplace Backup

2020-09-16 09:32 UTC, sasha-astiadi commented on src/3bot_sysadmin/admin_tools/3bot_backup.md
> +- right now visiting https://localhost/backup/actors/minio/restore will restore the last snapshot available
- Right now visiting https://localhost/backup/actors/minio/restore will restore the last snapshot available

2020-09-16 09:32 UTC, sasha-astiadi commented on src/3bot_sysadmin/admin_tools/3bot_backup.md
> +- if you want to restore the latest snapshot from shell
- If you want to restore the latest snapshot from shell

2020-09-16 09:32 UTC, sasha-astiadi commented on src/3bot_sysadmin/admin_tools/3bot_backup.md
> +- you can also restore to a specific snapshot using  `restore(target_path, snapshot_id=None)`
- You can also restore to a specific snapshot using  `restore(target_path, snapshot_id=None)`

2020-09-16 09:32 UTC, sasha-astiadi commented on src/3bot_sysadmin/admin_tools/3bot_capacity_explorer.md
> +This page let you explorer the TF Grid. It shows some statistics about the overall usage of the grid and the detail about all the nodes and gateways currently active.
This page lets you explore the TF Grid. It shows some statistics about the overall usage of the grid and the detail about all the active nodes and gateways.

2020-09-16 09:32 UTC, sasha-astiadi commented on src/3bot_sysadmin/admin_tools/3bot_deployed_workloads.md
> +The table let you filter workloads based on:
The table lets you filter workloads based on:

2020-09-16 09:32 UTC, sasha-astiadi commented on src/3bot_sysadmin/admin_tools/3bot_deployed_workloads.md
> +* **Capacity pool**: Only show workload linked to a certain capacity pool.
**Capacity Pools**: Only shows workload linked to a certain capacity pool.

2020-09-16 09:32 UTC, sasha-astiadi commented on src/3bot_sysadmin/admin_tools/3bot_deployed_workloads.md
> +* **Workload type**: Only show the workload of a certain type.
* **Workload Type**: Only shows the workload of a certain type.

2020-09-16 09:32 UTC, sasha-astiadi commented on src/3bot_sysadmin/admin_tools/3bot_deployed_workloads.md
> +* **Next Action**: Only show workload that are in a certain state.
**Next Action**: Only shows workload that are in a certain state.

2020-09-16 09:32 UTC, sasha-astiadi commented on src/3bot_sysadmin/admin_tools/3bot_deployed_workloads.md
> +This view will show you the most useful information based on the workload type. If you want to see the full workload detail as plain json, you can click the `More details` button.
This view will show you the most useful information based on the chosen workload type. If you want to see the full workload detail as plain json, you can click the `More details` button.

2020-09-16 09:32 UTC, sasha-astiadi commented on src/3bot_sysadmin/admin_tools/3bot_farm_mgmt.md
> +It can happen that one or more of your nodes die (hardware failure). If you want to clean it up and remove it from the farm, you can click the trash bin icon on the right side in the nodes tables.
It can happen that one or more of your nodes dies due to hardware failures. If you want to clean it up and remove it from the farm, you can click the trash bin icon on the right side in the nodes tables.

2020-09-16 09:32 UTC, sasha-astiadi commented on src/3bot_sysadmin/admin_tools/3bot_logs.md
>  Simply click on each __log message__ to see the detail of the log item.
Simply click on each __Log Message__ to see the detail of the log item.

2020-09-16 09:32 UTC, sasha-astiadi commented on src/3bot_sysadmin/admin_tools/3bot_settings.md
> +These options are targeted to developers that want to alter the behavior of the 3Bot to allow easier development experience.
These options are targeted to developers who want to alter the behavior of the 3Bot to allow an easier development experience.

2020-09-16 09:32 UTC, sasha-astiadi commented on src/3bot_sysadmin/admin_tools/3bot_settings.md
> +The settings section of the 3Bot allows you to manage who can access the 3Bot, the identities that the 3Bot can use and some developer oriented settings.
The settings section of the 3Bot allows you to manage who can access the 3Bot, the identities that the 3Bot can use and some developer-oriented settings.

2020-09-16 09:32 UTC, sasha-astiadi commented on src/3bot_sysadmin/admin_tools/3bot_settings.md
> +* **3Bot name**: This is the unique name associated with your identity (this must be the same as in the 3Bot connect application).
**3Bot Name**: This is the unique name associated with your identity (**3Bot name**: This is the unique name associated with your identity (this must be the same as in the 3Bot connect application).

2020-09-16 09:36 UTC, sasha-astiadi commented on src/3bot_sysadmin/admin_tools/3bot_logs.md
> +__3Bot Logs__ is an advance process administration system that aims to provide a history of each deployment process by recording all the logs and events throughout your entire 3Bot solutions' deploym
__3Bot Logs__ is an advance process administration system that aims to provide a history of each deployment process by recording all the logs and events throughout your entire 3Bot solutions' deployment processes. Here you can find the registry of process information, stages, bugs, or errors that occur for every deployment you have done in the past, complete with a filtering system of timestamp, categories, context, message and the process ID of each log

2020-09-16 12:56 UTC, merged